name: JS Linting

on:
  push:
    branches:
      - develop
      - main
    paths:
      - '**.js'
  pull_request:
    branches:
      - develop
    paths:
      - '**.js'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup node and npm cache
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Install Node dependencies
      run: npm ci --omit=optional

    - name: Get updated JS files
      id: changed-files
      uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32 # v46.0.1
      with:
        files: |
          **/*.js

    - name: Run JS linting
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      run: ./node_modules/.bin/10up-toolkit lint-js ${{ steps.changed-files.outputs.all_changed_files }}
