name: Plugin asset/readme update

on:
  push:
    branches:
    - main

jobs:
  main:
    name: Push to main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup node version
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Composer dependencies and dump autoload
        run: |
          composer install --no-dev --optimize-autoloader
          composer dump-autoload

      - name: Build
        run: |
          npm ci --no-optional
          npm run build

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@2480306f6f693672726d08b5917ea114cb2825f7 # v2.2.0
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: mailchimp
