name: Plugin asset/readme update

on:
  push:
    branches:
    - main

jobs:
  main:
    name: Push to main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node version
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Build
        run: |
          npm ci --no-optional
          npm run build

      - name: Install SVN
        run: |
          sudo apt-get update
          sudo apt-get install subversion

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: mailchimp
