name: Deploy to WordPress.org

on:
  release:
    types: [published]
  workflow_dispatch: # TODO: Delete after testing is complete

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node version and npm cache
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Build
      run: |
        npm ci --no-optional
        npm run build

    - name: Install SVN
      run: |
        sudo apt-get update
        sudo apt-get install subversion

    # TODO: Revert dummy changes after testing is successful
    
    - name: WordPress Plugin Deploy (dummy credentials used) # TODO: Rename after testing
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_USERNAME: "dummy-user" # TODO: Revert after testing
        SVN_PASSWORD: "dummy-pass" # TODO: Revert after testing
        SLUG: dummy-slug # TODO: Revert after testing
      continue-on-error: true # TODO: Remove after testing

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.deploy.outputs.zip-path }}
        body: |
          This release contains the latest updates for the WordPress plugin.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
