name: Deploy to WordPress.org

on:
  release:
    types: [published]

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.prerelease }} # Skip job if it is a pre-release

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup node version and npm cache
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install Composer dependencies and dump autoload
      run: |
        composer install --no-dev --optimize-autoloader
        composer dump-autoload

    - name: Build
      run: |
        npm ci --no-optional
        npm run build

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@54bd289b8525fd23a5c365ec369185f2966529c2 # v2.3.0
      with:
        generate-zip: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: mailchimp

    - name: Attach the wordpress.org plugin files to the Github release
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
      with:
        files: ${{ steps.deploy.outputs.zip-path }}
        body: |
          This release contains the latest updates for the WordPress plugin.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
